### ISSUE TITLE
proposal: overhaul the careers page

### ISSUE THREAD

**Issue by nylira** [tendermint/tendermint.com#133]
We can do way better than a list of jobs. We have to make Tendermint look more attractive to potential applicants, and the careers page is priority #1.

* a main page advertising our company
    * talk about work/life balance
    * talk about our company's mission
    * mention the benefits/perks of working at tendermint
    * remote/relocation opportunities
* a page showcasing our different teams--and how you can pick one to join, comms/marketing, UI, tendermint, cosmos-sdk, etc.
* a page with each of our offices, showing the layout, nice location photos, amenties of each office
* mention our development bounties as a way to contribute
* mention cosmos academy as a way to get started

**Comment by nylira** [comment]
* talk about our efforts to promote diversity
* a page about our interview process and how to correctly apply

**Comment by jolesbi** [comment]
@nylira makes a lot of sense to me!

**Comment by Chjango** [comment]
**Additional bullet point:**
- participating in the HackAtom as another potential avenue to employment
- adding Mandatory Task (i.e. Aliens) on top of Resume and Cover Letter to qualify

_Linking our internal open positions we'll need listed on the Careers page here too:_
[https://github.com/tendermint/hiring/projects]

# Careers—Template Content
## Headline/Company Mission
Tendermint is spearheading the next generation of blockchain-based applications. The Tendermint team is building state-of-the-art consensus and networking protocols to enable internet-scale distributed applications. Tendermint Core, the software product, is used as the foundational layer for Cosmos, the blockchain project which acts as the infrastructure for a decentralized Internet of Blockchains. Tendermint team members are passionate, self-driven leaders who will be playing an integral part in building a better, freer internet of tomorrow. Cosmos is one of the most exciting decentralized networks entering the token economy in 2018. Do you have what it takes to be a part of this movement?

## Work/life Balance
The company culture at Tendermint is a mixture of work and play. Distinctly, the line between either is blurred, since work _is_ play. Tendermint employees love what they do, and you would generally find them doing what they love during standard work hours and generally over the weekends. Since the Tendermint team is scattered across three major hubs (San Francisco, Toronto, and Berlin), employees work at all odd hours of the day, not being confined to a set work schedule. Collaboration and coordination occurs largely over GitHub, as the founders of Tendermint come from a background of serious open-source development.

## Benefits
- Healthcare & Dental Benefits for full-time employees
- Relocation benefits to one of the hubs (San Francisco, Toronto, Berlin)
- Remote work optionality

## Qualified Candidates are Required to Submit
- Completed task
- Resume
- Cover Letter
- (Technical Positions) GitHub page

## Interview Process—What to Expect
Qualified candidates can expect to go through a 3-round interview process. The first interview will be a screening call with HR. The second interview will be with the Project Manager of the relevant team applicants apply for. The final interview will be conducted with a C-level officer.

**Comment by jolesbi** [comment]
thanks for doing this @Chjango !

- `adding Mandatory Task` - i believe we're paying people for the time it takes to complete the technical task, so i'm not sure we can expect them to do this without us asking them to at the appropriate time in the process. we can share that technical hires can expect a technical task, but let's wait for the 2nd interviewer to share this task with candidates.

- `Headline/Company Mission` - section is really nice!

- `Work/life balance` - i have a few issues with this section...
1) though we can be a playful bunch, i think it's important to draw a clear line between work and play. we want to attract professionals and we are actively building professional software company. we have fun, but it's hard work. 

2) employees are welcome to work whenever they please, but there are expectations for being relatively in sync with whatever hub they are being hired at. this applies to working hours and weekends. i wouldn't mention that people on our team work on weekends and i don't think it's fair to expect other people to work on weekends.

- we'll have to check with arianne about "Healthcare & Dental Benefits for full-time employees". there may be some legal issues with full timers who are not in the country of residence of our hubs.

- it might be worth thinking of some questions to ask people to include in their cover letter. a lot of people won't answer the questions and that's a good way to weed out applicants who don't take this opportunity seriously.

📈 🚀 ✌️

**Comment by jessysaurusrex** [comment]
We should be extremely careful when talking about diversity-- even though we may have lots of support for diversity and inclusion internally, it's very early and our numbers aren't ready for prime time just yet. Plus, it's hard for us to speak authoritatively about diversity as an organization unless we've openly pledged support to community initiatives and and committed to regularly holding internal trainings or workshops like Ally Skills and unconscious bias training. (I care about these things and have ideas if anyone wants to work together to get them going.)

 It may be best to talk about diversity in terms of being committed to building a more diverse team, i.e. "We've charted an aggressive course to build a diverse, creative team. We're not there yet, but we are improving as our organization expands."

In terms of work/life balance, I agree with @jolesbi-- we should be careful about the work/play distinction, especially because it can have multiple meanings and connotations for different people in different points of their career. It might work to phrase things in terms of employees being in control of their own schedules, and that they work at their own pace in lieu of mentioning weekends.

**Comment by nylira** [comment]
Thanks for the good points made by everyone. Agreed that we have to be careful with the work/life balance and diversity points. Jessica will be taking over the content for this page and we'll use it to build a mockup for the new Careers index page.

**Comment by jolesbi** [comment]
@greg-szabo

**Comment by nylira** [comment]
Moving this to tendermint/internal.
